package com.qec.model.chart;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.qec.model.CitationJournalModel;
import com.qec.model.EmployeeModel;
import com.qec.model.UserModel;

/**
 * CitationJournal generated by hbm2java
 */
@Entity
@Table(name="citation_journal_details"
    ,catalog="qecdb"
)
public class CitationJournalChartModel  implements java.io.Serializable {


     private Long citationJournalDetailsId;
     private CitationJournalModel citationJournalModel;
     private String impactFactor;
     private String hecRecognize;
     private Double impactFactorValue;
     private Date dateof;
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="citation_journal_details_id", unique=true, nullable=false)
    public Long getCitationJournalDetailsId() {
        return this.citationJournalDetailsId;
    }
    
    public void setCitationJournalDetailsId(Long citationJournalDetailsId) {
        this.citationJournalDetailsId = citationJournalDetailsId;
    }
    
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="citation_journal_id")
	public CitationJournalModel getCitationJournalModel() {
		return citationJournalModel;
	}

	public void setCitationJournalModel(CitationJournalModel citationJournalModel) {
		this.citationJournalModel = citationJournalModel;
	}
     
    @Column(name="impact_factor", length=250)
    public String getImpactFactor() {
        return this.impactFactor;
    }
    
    public void setImpactFactor(String impactFactor) {
        this.impactFactor = impactFactor;
    }
    
    @Column(name="hec_recognize", length=3)
    public String getHecRecognize() {
        return this.hecRecognize;
    }
    
    public void setHecRecognize(String hecRecognize) {
        this.hecRecognize = hecRecognize;
    }
    
    @Column(name="impact_factor_value", precision=22, scale=0)
    public Double getImpactFactorValue() {
        return this.impactFactorValue;
    }
    
    public void setImpactFactorValue(Double impactFactorValue) {
        this.impactFactorValue = impactFactorValue;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateof", length=10)
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
}


