package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Bugs generated by hbm2java
 */
public class Bugs  implements java.io.Serializable {


     private Long bugsId;
     private UserDTO user;
     private String detail;
     private String images;
     private Date dateof;

    public Bugs() {
    }

    public Bugs(UserDTO user, String detail, String images, Date dateof) {
       this.user = user;
       this.detail = detail;
       this.images = images;
       this.dateof = dateof;
    }
   
    public Long getBugsId() {
        return this.bugsId;
    }
    
    public void setBugsId(Long bugsId) {
        this.bugsId = bugsId;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }




}


