package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA



/**
 * Campuses generated by hbm2java
 */
public class Campuses  implements java.io.Serializable {


     private Long campusesId;
     private String campusName;

    public Campuses() {
    }

    public Campuses(String campusName) {
       this.campusName = campusName;
    }
   
    public Long getCampusesId() {
        return this.campusesId;
    }
    
    public void setCampusesId(Long campusesId) {
        this.campusesId = campusesId;
    }
    public String getCampusName() {
        return this.campusName;
    }
    
    public void setCampusName(String campusName) {
        this.campusName = campusName;
    }




}


