package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CitationConference generated by hbm2java
 */
public class CitationConferenceDTO  implements java.io.Serializable {

	private Long citationConferenceId;
    private Long employeeId;
    private EmployeeDTO employee;
    private UserDTO user;
    private String title;
    private String url;
    private String authors;
    private Date publicationDate;
    private String conference;
    private Long volume;
    private Long issue;
    private String pages;
    private String publisher;
    private String description;
    private String impactFactor;
    private String hecRecognize;
    private Double impactFactorValue;
    private Byte isDeleted;
     
    public Long getCitationConferenceId() {
        return this.citationConferenceId;
    }
    
    public void setCitationConferenceId(Long citationConferenceId) {
        this.citationConferenceId = citationConferenceId;
    }

	public Long getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}
	public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(String authors) {
        this.authors = authors;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getConference() {
        return this.conference;
    }
    
    public void setConference(String conference) {
        this.conference = conference;
    }
    public Long getVolume() {
        return this.volume;
    }
    
    public void setVolume(Long volume) {
        this.volume = volume;
    }
    public Long getIssue() {
        return this.issue;
    }
    
    public void setIssue(Long issue) {
        this.issue = issue;
    }
    public String getPages() {
        return this.pages;
    }
    
    public void setPages(String pages) {
        this.pages = pages;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImpactFactor() {
        return this.impactFactor;
    }
    
    public void setImpactFactor(String impactFactor) {
        this.impactFactor = impactFactor;
    }
    public String getHecRecognize() {
        return this.hecRecognize;
    }
    
    public void setHecRecognize(String hecRecognize) {
        this.hecRecognize = hecRecognize;
    }
    public Double getImpactFactorValue() {
        return this.impactFactorValue;
    }
    
    public void setImpactFactorValue(Double impactFactorValue) {
        this.impactFactorValue = impactFactorValue;
    }

	public Byte getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}
}