package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CitationPatent generated by hbm2java
 */
public class CitationPatent  implements java.io.Serializable {


     private Long citationPatentId;
     private Employee employee;
     private UserDTO user;
     private String title;
     private String url;
     private String inventors;
     private Date publicationDate;
     private String patentOffice;
     private String patentNumber;
     private String applicationNumber;
     private String description;

    public CitationPatent() {
    }

    public CitationPatent(Employee employee, UserDTO user, String title, String url, String inventors, Date publicationDate, String patentOffice, String patentNumber, String applicationNumber, String description) {
       this.employee = employee;
       this.user = user;
       this.title = title;
       this.url = url;
       this.inventors = inventors;
       this.publicationDate = publicationDate;
       this.patentOffice = patentOffice;
       this.patentNumber = patentNumber;
       this.applicationNumber = applicationNumber;
       this.description = description;
    }
   
    public Long getCitationPatentId() {
        return this.citationPatentId;
    }
    
    public void setCitationPatentId(Long citationPatentId) {
        this.citationPatentId = citationPatentId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getInventors() {
        return this.inventors;
    }
    
    public void setInventors(String inventors) {
        this.inventors = inventors;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getPatentOffice() {
        return this.patentOffice;
    }
    
    public void setPatentOffice(String patentOffice) {
        this.patentOffice = patentOffice;
    }
    public String getPatentNumber() {
        return this.patentNumber;
    }
    
    public void setPatentNumber(String patentNumber) {
        this.patentNumber = patentNumber;
    }
    public String getApplicationNumber() {
        return this.applicationNumber;
    }
    
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


