package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import com.qec.model.CitationJournalModel;

/**
 * CitationJournal generated by hbm2java
 */
public class CitationJournal  implements java.io.Serializable {


    private CitationJournalModel citationJournalModel;
    private Long x;
    private Long y;
     
	public CitationJournalModel getCitationJournalModel() 
	{
		return citationJournalModel;
	}
	public void setCitationJournalModel(CitationJournalModel citationJournalModel) 
	{
		this.citationJournalModel = citationJournalModel;
	}
	public Long getX() 
	{
		return x;
	}
	public void setX(Long x) 
	{
		this.x = x;
	}
	public Long getY() 
	{
		return y;
	}
	public void setY(Long y) 
	{
		this.y = y;
	}
     
     




}


