package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA

/**
 * GoogleCitation generated by hbm2java
 */
public class CitationGoogleDTO  implements java.io.Serializable {

    private Long citationGoogleId;
    private EmployeeDTO employee;
    private String employeeName;
    private Long employeeId;
    private UserDTO user;
    private String url;
    private String isDeleted;
   
    public Long getCitationGoogleId() {
        return this.citationGoogleId;
    }
    
    public void setCitationGoogleId(Long citationGoogleId) {
        this.citationGoogleId = citationGoogleId;
    }
    public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }

    public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Long getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

	public String getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}
}