package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CitationConference generated by hbm2java
 */
public class CitationConference  implements java.io.Serializable {


     private Long citationConference;
     private EmployeeDTO employee;
     private UserDTO user;
     private String title;
     private String url;
     private String authors;
     private Date publicationDate;
     private String conference;
     private Long volume;
     private Long issue;
     private String pages;
     private String publisher;
     private String description;
     private String impactFactor;
     private String hecRecognize;
     private Double impactFactorValue;

    public CitationConference() {
    }

    public CitationConference(EmployeeDTO employee, UserDTO user, String title, String url, String authors, Date publicationDate, String conference, Long volume, Long issue, String pages, String publisher, String description, String impactFactor, String hecRecognize, Double impactFactorValue) {
       this.employee = employee;
       this.user = user;
       this.title = title;
       this.url = url;
       this.authors = authors;
       this.publicationDate = publicationDate;
       this.conference = conference;
       this.volume = volume;
       this.issue = issue;
       this.pages = pages;
       this.publisher = publisher;
       this.description = description;
       this.impactFactor = impactFactor;
       this.hecRecognize = hecRecognize;
       this.impactFactorValue = impactFactorValue;
    }
   
    public Long getCitationConference() {
        return this.citationConference;
    }
    
    public void setCitationConference(Long citationConference) {
        this.citationConference = citationConference;
    }
    public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(String authors) {
        this.authors = authors;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getConference() {
        return this.conference;
    }
    
    public void setConference(String conference) {
        this.conference = conference;
    }
    public Long getVolume() {
        return this.volume;
    }
    
    public void setVolume(Long volume) {
        this.volume = volume;
    }
    public Long getIssue() {
        return this.issue;
    }
    
    public void setIssue(Long issue) {
        this.issue = issue;
    }
    public String getPages() {
        return this.pages;
    }
    
    public void setPages(String pages) {
        this.pages = pages;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImpactFactor() {
        return this.impactFactor;
    }
    
    public void setImpactFactor(String impactFactor) {
        this.impactFactor = impactFactor;
    }
    public String getHecRecognize() {
        return this.hecRecognize;
    }
    
    public void setHecRecognize(String hecRecognize) {
        this.hecRecognize = hecRecognize;
    }
    public Double getImpactFactorValue() {
        return this.impactFactorValue;
    }
    
    public void setImpactFactorValue(Double impactFactorValue) {
        this.impactFactorValue = impactFactorValue;
    }




}


