package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CitationOther generated by hbm2java
 */
public class CitationOther  implements java.io.Serializable {


     private Long citationOtherId;
     private Employee employee;
     private UserDTO user;
     private String title;
     private String url;
     private String authors;
     private Date publicationDate;
     private String source;
     private String reportNumber;
     private String description;

    public CitationOther() {
    }

    public CitationOther(Employee employee, UserDTO user, String title, String url, String authors, Date publicationDate, String source, String reportNumber, String description) {
       this.employee = employee;
       this.user = user;
       this.title = title;
       this.url = url;
       this.authors = authors;
       this.publicationDate = publicationDate;
       this.source = source;
       this.reportNumber = reportNumber;
       this.description = description;
    }
   
    public Long getCitationOtherId() {
        return this.citationOtherId;
    }
    
    public void setCitationOtherId(Long citationOtherId) {
        this.citationOtherId = citationOtherId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(String authors) {
        this.authors = authors;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getReportNumber() {
        return this.reportNumber;
    }
    
    public void setReportNumber(String reportNumber) {
        this.reportNumber = reportNumber;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


