package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CitationThesis generated by hbm2java
 */
public class CitationThesis  implements java.io.Serializable {


     private Long citationThesisId;
     private Employee employee;
     private UserDTO user;
     private String title;
     private String url;
     private String authors;
     private Date publicationDate;
     private String institution;
     private String description;

    public CitationThesis() {
    }

    public CitationThesis(Employee employee, UserDTO user, String title, String url, String authors, Date publicationDate, String institution, String description) {
       this.employee = employee;
       this.user = user;
       this.title = title;
       this.url = url;
       this.authors = authors;
       this.publicationDate = publicationDate;
       this.institution = institution;
       this.description = description;
    }
   
    public Long getCitationThesisId() {
        return this.citationThesisId;
    }
    
    public void setCitationThesisId(Long citationThesisId) {
        this.citationThesisId = citationThesisId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(String authors) {
        this.authors = authors;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


