package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private Long citiesId;
     private String cityName;
     private String province;
     private String abbrivation;
     private Set empTrainingses = new HashSet(0);
     private Set empTravelgrandses = new HashSet(0);
     private Set studentScholarshipses = new HashSet(0);
     private Set employeesEducations = new HashSet(0);

    public Cities() {
    }

    public Cities(String cityName, String province, String abbrivation, Set empTrainingses, Set empTravelgrandses, Set studentScholarshipses, Set employeesEducations) {
       this.cityName = cityName;
       this.province = province;
       this.abbrivation = abbrivation;
       this.empTrainingses = empTrainingses;
       this.empTravelgrandses = empTravelgrandses;
       this.studentScholarshipses = studentScholarshipses;
       this.employeesEducations = employeesEducations;
    }
   
    public Long getCitiesId() {
        return this.citiesId;
    }
    
    public void setCitiesId(Long citiesId) {
        this.citiesId = citiesId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getAbbrivation() {
        return this.abbrivation;
    }
    
    public void setAbbrivation(String abbrivation) {
        this.abbrivation = abbrivation;
    }
    public Set getEmpTrainingses() {
        return this.empTrainingses;
    }
    
    public void setEmpTrainingses(Set empTrainingses) {
        this.empTrainingses = empTrainingses;
    }
    public Set getEmpTravelgrandses() {
        return this.empTravelgrandses;
    }
    
    public void setEmpTravelgrandses(Set empTravelgrandses) {
        this.empTravelgrandses = empTravelgrandses;
    }
    public Set getStudentScholarshipses() {
        return this.studentScholarshipses;
    }
    
    public void setStudentScholarshipses(Set studentScholarshipses) {
        this.studentScholarshipses = studentScholarshipses;
    }
    public Set getEmployeesEducations() {
        return this.employeesEducations;
    }
    
    public void setEmployeesEducations(Set employeesEducations) {
        this.employeesEducations = employeesEducations;
    }




}


