package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Countries generated by hbm2java
 */
public class Countries  implements java.io.Serializable {


     private Long countriesId;
     private String countryName;
     private Set empTrainingses = new HashSet(0);
     private Set studentScholarshipses = new HashSet(0);
     private Set empTravelgrandses = new HashSet(0);

    public Countries() {
    }

    public Countries(String countryName, Set empTrainingses, Set studentScholarshipses, Set empTravelgrandses) {
       this.countryName = countryName;
       this.empTrainingses = empTrainingses;
       this.studentScholarshipses = studentScholarshipses;
       this.empTravelgrandses = empTravelgrandses;
    }
   
    public Long getCountriesId() {
        return this.countriesId;
    }
    
    public void setCountriesId(Long countriesId) {
        this.countriesId = countriesId;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public Set getEmpTrainingses() {
        return this.empTrainingses;
    }
    
    public void setEmpTrainingses(Set empTrainingses) {
        this.empTrainingses = empTrainingses;
    }
    public Set getStudentScholarshipses() {
        return this.studentScholarshipses;
    }
    
    public void setStudentScholarshipses(Set studentScholarshipses) {
        this.studentScholarshipses = studentScholarshipses;
    }
    public Set getEmpTravelgrandses() {
        return this.empTravelgrandses;
    }
    
    public void setEmpTravelgrandses(Set empTravelgrandses) {
        this.empTravelgrandses = empTravelgrandses;
    }




}


