package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private Long departmentId;
     private String name;
     private String detail;
     private Byte isDeleted;
     private Set eventses = new HashSet(0);
     private Set accreditationses = new HashSet(0);
     private Set uniProgramses = new HashSet(0);
     private Set empPhdstrategies = new HashSet(0);
     private Set employeesServiceses = new HashSet(0);
     private Set promotionses = new HashSet(0);
     private Set employees = new HashSet(0);

    public Departments() {
    }

    public Departments(String name, String detail, Byte isDeleted, Set eventses, Set accreditationses, Set uniProgramses, Set empPhdstrategies, Set employeesServiceses, Set promotionses, Set employees) {
       this.name = name;
       this.detail = detail;
       this.isDeleted = isDeleted;
       this.eventses = eventses;
       this.accreditationses = accreditationses;
       this.uniProgramses = uniProgramses;
       this.empPhdstrategies = empPhdstrategies;
       this.employeesServiceses = employeesServiceses;
       this.promotionses = promotionses;
       this.employees = employees;
    }
   
    public Long getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getEventses() {
        return this.eventses;
    }
    
    public void setEventses(Set eventses) {
        this.eventses = eventses;
    }
    public Set getAccreditationses() {
        return this.accreditationses;
    }
    
    public void setAccreditationses(Set accreditationses) {
        this.accreditationses = accreditationses;
    }
    public Set getUniProgramses() {
        return this.uniProgramses;
    }
    
    public void setUniProgramses(Set uniProgramses) {
        this.uniProgramses = uniProgramses;
    }
    public Set getEmpPhdstrategies() {
        return this.empPhdstrategies;
    }
    
    public void setEmpPhdstrategies(Set empPhdstrategies) {
        this.empPhdstrategies = empPhdstrategies;
    }
    public Set getEmployeesServiceses() {
        return this.employeesServiceses;
    }
    
    public void setEmployeesServiceses(Set employeesServiceses) {
        this.employeesServiceses = employeesServiceses;
    }
    public Set getPromotionses() {
        return this.promotionses;
    }
    
    public void setPromotionses(Set promotionses) {
        this.promotionses = promotionses;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


