package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EmpCommunityservices generated by hbm2java
 */
public class EmpCommunityservices  implements java.io.Serializable {


     private Long empCommunityservicesId;
     private EmployeeDTO employee;
     private String name;
     private Date dateof;
     private String place;
     private String file;

    public EmpCommunityservices() {
    }

    public EmpCommunityservices(EmployeeDTO employee, String name, Date dateof, String place, String file) {
       this.employee = employee;
       this.name = name;
       this.dateof = dateof;
       this.place = place;
       this.file = file;
    }
   
    public Long getEmpCommunityservicesId() {
        return this.empCommunityservicesId;
    }
    
    public void setEmpCommunityservicesId(Long empCommunityservicesId) {
        this.empCommunityservicesId = empCommunityservicesId;
    }
    public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }




}


