package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EmpIndustriallinkages generated by hbm2java
 */
public class EmpIndustriallinkages  implements java.io.Serializable {


     private Long empIndustriallinkagesId;
     private EmployeeDTO employee;
     private String nameOfOrg;
     private Date dateof;
     private String purposeOfLinkage;
     private Date startDuration;
     private Long endDuration;
     private String file;

    public EmpIndustriallinkages() {
    }

    public EmpIndustriallinkages(EmployeeDTO employee, String nameOfOrg, Date dateof, String purposeOfLinkage, Date startDuration, Long endDuration, String file) {
       this.employee = employee;
       this.nameOfOrg = nameOfOrg;
       this.dateof = dateof;
       this.purposeOfLinkage = purposeOfLinkage;
       this.startDuration = startDuration;
       this.endDuration = endDuration;
       this.file = file;
    }
   
    public Long getEmpIndustriallinkagesId() {
        return this.empIndustriallinkagesId;
    }
    
    public void setEmpIndustriallinkagesId(Long empIndustriallinkagesId) {
        this.empIndustriallinkagesId = empIndustriallinkagesId;
    }
    public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }
    public String getNameOfOrg() {
        return this.nameOfOrg;
    }
    
    public void setNameOfOrg(String nameOfOrg) {
        this.nameOfOrg = nameOfOrg;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    public String getPurposeOfLinkage() {
        return this.purposeOfLinkage;
    }
    
    public void setPurposeOfLinkage(String purposeOfLinkage) {
        this.purposeOfLinkage = purposeOfLinkage;
    }
    public Date getStartDuration() {
        return this.startDuration;
    }
    
    public void setStartDuration(Date startDuration) {
        this.startDuration = startDuration;
    }
    public Long getEndDuration() {
        return this.endDuration;
    }
    
    public void setEndDuration(Long endDuration) {
        this.endDuration = endDuration;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }




}


