package com.qec.dto;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpTrainings generated by hbm2java
 */
public class EmployeeTrainingDTO  implements java.io.Serializable {

	private Long employeeTrainingsId;
    private EmployeeDTO employee;
    private Long employeeId;
    private Countries countries;
    private Cities cities;
    private String name;
    private String place;
    private String file;
    private String locality;
    private String instituteName;
    private String trainingCondition;
    private String dateof;
    private String fundingDetail;
    private Boolean isDeleted;
     
	public Long getEmployeeTrainingsId() {
		return employeeTrainingsId;
	}
	
	public void setEmployeeTrainingsId(Long employeeTrainingsId) {
		this.employeeTrainingsId = employeeTrainingsId;
	}
	
	public EmployeeDTO getEmployee() {
		return employee;
	}
	
	public void setEmployee(EmployeeDTO employee) {
		this.employee = employee;
	}
	
	public Long getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	public Countries getCountries() {
		return countries;
	}
	
	public void setCountries(Countries countries) {
		this.countries = countries;
	}
	
	public Cities getCities() {
		return cities;
	}
	
	public void setCities(Cities cities) {
		this.cities = cities;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getPlace() {
		return place;
	}
	
	public void setPlace(String place) {
		this.place = place;
	}
	
	public String getFile() {
		return file;
	}
	
	public void setFile(String file) {
		this.file = file;
	}
	
	public String getLocality() {
		return locality;
	}
	
	public void setLocality(String locality) {
		this.locality = locality;
	}
	
	public String getInstituteName() {
		return instituteName;
	}

	public void setInstituteName(String instituteName) {
		this.instituteName = instituteName;
	}
	
	public String getTrainingCondition() {
		return trainingCondition;
	}
	
	public void setTrainingCondition(String trainingCondition) {
		this.trainingCondition = trainingCondition;
	}
	
	public String getDateof() {
		return dateof;
	}
	
	public void setDateof(String dateof) {
		this.dateof = dateof;
	}
	
	public String getFundingDetail() {
		return fundingDetail;
	}
	
	public void setFundingDetail(String fundingDetail) {
		this.fundingDetail = fundingDetail;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
}