package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Long employeeId;
     private Departments departments;
     private String title;
     private String fullName;
     private String surname;
     private String cast;
     private String maritalStatus;
     private String fatherName;
     private String husbandName;
     private String email;
     private String postalAddress;
     private String presentAddress;
     private String nic;
     private Date dob;
     private String gender;
     private String mobile;
     private String phone;
     private String religion;
     private String country;
     private String imgPath;
     private Byte isDeleted;
     private Set citationOthers = new HashSet(0);
     private Set googleCitations = new HashSet(0);
     private Set empTravelgrandses = new HashSet(0);
     private Set citationConferences = new HashSet(0);
     private Set employeesServiceses = new HashSet(0);
     private Set empPhdstrategies = new HashSet(0);
     private Set citationBooks = new HashSet(0);
     private Set citationPatents = new HashSet(0);
     private Set empTrainingses = new HashSet(0);
     private Set employeesEducations = new HashSet(0);
     private Set empIndustriallinkageses = new HashSet(0);
     private Set citationJournals = new HashSet(0);
     private Set empCommunityserviceses = new HashSet(0);
     private Set promotionses = new HashSet(0);
     private Set citationThesises = new HashSet(0);
     private Set citationChapters = new HashSet(0);
     private Set employeesCitations = new HashSet(0);
     private Set users = new HashSet(0);

    public Employee() {
    }

    public Employee(Departments departments, String title, String fullName, String surname, String cast, String maritalStatus, String fatherName, String husbandName, String email, String postalAddress, String presentAddress, String nic, Date dob, String gender, String mobile, String phone, String religion, String country, String imgPath, Byte isDeleted, Set citationOthers, Set googleCitations, Set empTravelgrandses, Set citationConferences, Set employeesServiceses, Set empPhdstrategies, Set citationBooks, Set citationPatents, Set empTrainingses, Set employeesEducations, Set empIndustriallinkageses, Set citationJournals, Set empCommunityserviceses, Set promotionses, Set citationThesises, Set citationChapters, Set employeesCitations, Set users) {
       this.departments = departments;
       this.title = title;
       this.fullName = fullName;
       this.surname = surname;
       this.cast = cast;
       this.maritalStatus = maritalStatus;
       this.fatherName = fatherName;
       this.husbandName = husbandName;
       this.email = email;
       this.postalAddress = postalAddress;
       this.presentAddress = presentAddress;
       this.nic = nic;
       this.dob = dob;
       this.gender = gender;
       this.mobile = mobile;
       this.phone = phone;
       this.religion = religion;
       this.country = country;
       this.imgPath = imgPath;
       this.isDeleted = isDeleted;
       this.citationOthers = citationOthers;
       this.googleCitations = googleCitations;
       this.empTravelgrandses = empTravelgrandses;
       this.citationConferences = citationConferences;
       this.employeesServiceses = employeesServiceses;
       this.empPhdstrategies = empPhdstrategies;
       this.citationBooks = citationBooks;
       this.citationPatents = citationPatents;
       this.empTrainingses = empTrainingses;
       this.employeesEducations = employeesEducations;
       this.empIndustriallinkageses = empIndustriallinkageses;
       this.citationJournals = citationJournals;
       this.empCommunityserviceses = empCommunityserviceses;
       this.promotionses = promotionses;
       this.citationThesises = citationThesises;
       this.citationChapters = citationChapters;
       this.employeesCitations = employeesCitations;
       this.users = users;
    }
   
    public Long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getCast() {
        return this.cast;
    }
    
    public void setCast(String cast) {
        this.cast = cast;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    public String getHusbandName() {
        return this.husbandName;
    }
    
    public void setHusbandName(String husbandName) {
        this.husbandName = husbandName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPostalAddress() {
        return this.postalAddress;
    }
    
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress;
    }
    public String getPresentAddress() {
        return this.presentAddress;
    }
    
    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getCitationOthers() {
        return this.citationOthers;
    }
    
    public void setCitationOthers(Set citationOthers) {
        this.citationOthers = citationOthers;
    }
    public Set getGoogleCitations() {
        return this.googleCitations;
    }
    
    public void setGoogleCitations(Set googleCitations) {
        this.googleCitations = googleCitations;
    }
    public Set getEmpTravelgrandses() {
        return this.empTravelgrandses;
    }
    
    public void setEmpTravelgrandses(Set empTravelgrandses) {
        this.empTravelgrandses = empTravelgrandses;
    }
    public Set getCitationConferences() {
        return this.citationConferences;
    }
    
    public void setCitationConferences(Set citationConferences) {
        this.citationConferences = citationConferences;
    }
    public Set getEmployeesServiceses() {
        return this.employeesServiceses;
    }
    
    public void setEmployeesServiceses(Set employeesServiceses) {
        this.employeesServiceses = employeesServiceses;
    }
    public Set getEmpPhdstrategies() {
        return this.empPhdstrategies;
    }
    
    public void setEmpPhdstrategies(Set empPhdstrategies) {
        this.empPhdstrategies = empPhdstrategies;
    }
    public Set getCitationBooks() {
        return this.citationBooks;
    }
    
    public void setCitationBooks(Set citationBooks) {
        this.citationBooks = citationBooks;
    }
    public Set getCitationPatents() {
        return this.citationPatents;
    }
    
    public void setCitationPatents(Set citationPatents) {
        this.citationPatents = citationPatents;
    }
    public Set getEmpTrainingses() {
        return this.empTrainingses;
    }
    
    public void setEmpTrainingses(Set empTrainingses) {
        this.empTrainingses = empTrainingses;
    }
    public Set getEmployeesEducations() {
        return this.employeesEducations;
    }
    
    public void setEmployeesEducations(Set employeesEducations) {
        this.employeesEducations = employeesEducations;
    }
    public Set getEmpIndustriallinkageses() {
        return this.empIndustriallinkageses;
    }
    
    public void setEmpIndustriallinkageses(Set empIndustriallinkageses) {
        this.empIndustriallinkageses = empIndustriallinkageses;
    }
    public Set getCitationJournals() {
        return this.citationJournals;
    }
    
    public void setCitationJournals(Set citationJournals) {
        this.citationJournals = citationJournals;
    }
    public Set getEmpCommunityserviceses() {
        return this.empCommunityserviceses;
    }
    
    public void setEmpCommunityserviceses(Set empCommunityserviceses) {
        this.empCommunityserviceses = empCommunityserviceses;
    }
    public Set getPromotionses() {
        return this.promotionses;
    }
    
    public void setPromotionses(Set promotionses) {
        this.promotionses = promotionses;
    }
    public Set getCitationThesises() {
        return this.citationThesises;
    }
    
    public void setCitationThesises(Set citationThesises) {
        this.citationThesises = citationThesises;
    }
    public Set getCitationChapters() {
        return this.citationChapters;
    }
    
    public void setCitationChapters(Set citationChapters) {
        this.citationChapters = citationChapters;
    }
    public Set getEmployeesCitations() {
        return this.employeesCitations;
    }
    
    public void setEmployeesCitations(Set employeesCitations) {
        this.employeesCitations = employeesCitations;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


