package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EmployeesCitation generated by hbm2java
 */
public class EmployeesCitation  implements java.io.Serializable {


     private Long empTravelgrandsId;
     private Employee employee;
     private String title;
     private String url;
     private String authors;
     private Date publicationDate;
     private String journal;
     private Long volume;
     private Long issue;
     private String pages;
     private String publisher;
     private String description;

    public EmployeesCitation() {
    }

    public EmployeesCitation(Employee employee, String title, String url, String authors, Date publicationDate, String journal, Long volume, Long issue, String pages, String publisher, String description) {
       this.employee = employee;
       this.title = title;
       this.url = url;
       this.authors = authors;
       this.publicationDate = publicationDate;
       this.journal = journal;
       this.volume = volume;
       this.issue = issue;
       this.pages = pages;
       this.publisher = publisher;
       this.description = description;
    }
   
    public Long getEmpTravelgrandsId() {
        return this.empTravelgrandsId;
    }
    
    public void setEmpTravelgrandsId(Long empTravelgrandsId) {
        this.empTravelgrandsId = empTravelgrandsId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(String authors) {
        this.authors = authors;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getJournal() {
        return this.journal;
    }
    
    public void setJournal(String journal) {
        this.journal = journal;
    }
    public Long getVolume() {
        return this.volume;
    }
    
    public void setVolume(Long volume) {
        this.volume = volume;
    }
    public Long getIssue() {
        return this.issue;
    }
    
    public void setIssue(Long issue) {
        this.issue = issue;
    }
    public String getPages() {
        return this.pages;
    }
    
    public void setPages(String pages) {
        this.pages = pages;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


