package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EmpPhdstrategy generated by hbm2java
 */
public class EmpPhdstrategy  implements java.io.Serializable {


     private Long empPhdstrategyId;
     private Employee employee;
     private Departments departments;
     private String studentName;
     private String dtype;
     private Double noOfStudents;
     private Date startDate;
     private Date regDate;
     private Double rollNo;
     private String file;
     private String topic;

    public EmpPhdstrategy() {
    }

    public EmpPhdstrategy(Employee employee, Departments departments, String studentName, String dtype, Double noOfStudents, Date startDate, Date regDate, Double rollNo, String file, String topic) {
       this.employee = employee;
       this.departments = departments;
       this.studentName = studentName;
       this.dtype = dtype;
       this.noOfStudents = noOfStudents;
       this.startDate = startDate;
       this.regDate = regDate;
       this.rollNo = rollNo;
       this.file = file;
       this.topic = topic;
    }
   
    public Long getEmpPhdstrategyId() {
        return this.empPhdstrategyId;
    }
    
    public void setEmpPhdstrategyId(Long empPhdstrategyId) {
        this.empPhdstrategyId = empPhdstrategyId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getDtype() {
        return this.dtype;
    }
    
    public void setDtype(String dtype) {
        this.dtype = dtype;
    }
    public Double getNoOfStudents() {
        return this.noOfStudents;
    }
    
    public void setNoOfStudents(Double noOfStudents) {
        this.noOfStudents = noOfStudents;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public Double getRollNo() {
        return this.rollNo;
    }
    
    public void setRollNo(Double rollNo) {
        this.rollNo = rollNo;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }




}


