package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Events generated by hbm2java
 */
public class Events  implements java.io.Serializable {


     private Long eventsId;
     private UserDTO user;
     private Departments departments;
     private String eventTitle;
     private Date dateof;
     private Date endDate;
     private Double quota;
     private String eventDetail;
     private String color;
     private Byte isDeleted;
     private Set imageses = new HashSet(0);

    public Events() {
    }

    public Events(UserDTO user, Departments departments, String eventTitle, Date dateof, Date endDate, Double quota, String eventDetail, String color, Byte isDeleted, Set imageses) {
       this.user = user;
       this.departments = departments;
       this.eventTitle = eventTitle;
       this.dateof = dateof;
       this.endDate = endDate;
       this.quota = quota;
       this.eventDetail = eventDetail;
       this.color = color;
       this.isDeleted = isDeleted;
       this.imageses = imageses;
    }
   
    public Long getEventsId() {
        return this.eventsId;
    }
    
    public void setEventsId(Long eventsId) {
        this.eventsId = eventsId;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public String getEventTitle() {
        return this.eventTitle;
    }
    
    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Double getQuota() {
        return this.quota;
    }
    
    public void setQuota(Double quota) {
        this.quota = quota;
    }
    public String getEventDetail() {
        return this.eventDetail;
    }
    
    public void setEventDetail(String eventDetail) {
        this.eventDetail = eventDetail;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }




}


