package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private Long facultyId;
     private String facultyName;
     private Set uniDepartmentses = new HashSet(0);
     private Set accreditationses = new HashSet(0);
     private Set employeesServiceses = new HashSet(0);

    public Faculty() {
    }

	
    public Faculty(String facultyName) {
        this.facultyName = facultyName;
    }
    public Faculty(String facultyName, Set uniDepartmentses, Set accreditationses, Set employeesServiceses) {
       this.facultyName = facultyName;
       this.uniDepartmentses = uniDepartmentses;
       this.accreditationses = accreditationses;
       this.employeesServiceses = employeesServiceses;
    }
   
    public Long getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }
    public String getFacultyName() {
        return this.facultyName;
    }
    
    public void setFacultyName(String facultyName) {
        this.facultyName = facultyName;
    }
    public Set getUniDepartmentses() {
        return this.uniDepartmentses;
    }
    
    public void setUniDepartmentses(Set uniDepartmentses) {
        this.uniDepartmentses = uniDepartmentses;
    }
    public Set getAccreditationses() {
        return this.accreditationses;
    }
    
    public void setAccreditationses(Set accreditationses) {
        this.accreditationses = accreditationses;
    }
    public Set getEmployeesServiceses() {
        return this.employeesServiceses;
    }
    
    public void setEmployeesServiceses(Set employeesServiceses) {
        this.employeesServiceses = employeesServiceses;
    }




}


