package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class FacultyDTO  implements java.io.Serializable {

	private Long facultyId;
    private String facultyName;

	public Long getFacultyId() {
		return this.facultyId;
	}
	    
	public void setFacultyId(Long facultyId) {
		this.facultyId = facultyId;
	}
	
	public String getFacultyName() {
		return this.facultyName;
	}
	    
	public void setFacultyName(String facultyName) {
		this.facultyName = facultyName;
	}
}


