package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA



/**
 * GoogleCitation generated by hbm2java
 */
public class GoogleCitation  implements java.io.Serializable {


     private Long googleCitationId;
     private EmployeeDTO employee;
     private UserDTO user;
     private String url;

    public GoogleCitation() {
    }

   
    public Long getGoogleCitationId() {
        return this.googleCitationId;
    }
    
    public void setGoogleCitationId(Long googleCitationId) {
        this.googleCitationId = googleCitationId;
    }
    public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


