package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Institutions generated by hbm2java
 */
public class Institutions  implements java.io.Serializable {


     private Long institutionsId;
     private String institutionName;
     private Byte isUniversity;
     private Set studentScholarshipses = new HashSet(0);

    public Institutions() {
    }

    public Institutions(String institutionName, Byte isUniversity, Set studentScholarshipses) {
       this.institutionName = institutionName;
       this.isUniversity = isUniversity;
       this.studentScholarshipses = studentScholarshipses;
    }
   
    public Long getInstitutionsId() {
        return this.institutionsId;
    }
    
    public void setInstitutionsId(Long institutionsId) {
        this.institutionsId = institutionsId;
    }
    public String getInstitutionName() {
        return this.institutionName;
    }
    
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }
    public Byte getIsUniversity() {
        return this.isUniversity;
    }
    
    public void setIsUniversity(Byte isUniversity) {
        this.isUniversity = isUniversity;
    }
    public Set getStudentScholarshipses() {
        return this.studentScholarshipses;
    }
    
    public void setStudentScholarshipses(Set studentScholarshipses) {
        this.studentScholarshipses = studentScholarshipses;
    }




}


