package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LoginsHistory generated by hbm2java
 */
public class LoginsHistory  implements java.io.Serializable {


     private Long loginsHistoryId;
     private UserDTO user;
     private Date dateof;
     private Date startTime;
     private Date endTime;

    public LoginsHistory() {
    }

    public LoginsHistory(UserDTO user, Date dateof, Date startTime, Date endTime) {
       this.user = user;
       this.dateof = dateof;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public Long getLoginsHistoryId() {
        return this.loginsHistoryId;
    }
    
    public void setLoginsHistoryId(Long loginsHistoryId) {
        this.loginsHistoryId = loginsHistoryId;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


