package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProgramHistory generated by hbm2java
 */
public class ProgramHistory  implements java.io.Serializable {


     private Long programHistoryId;
     private UniPrograms uniPrograms;
     private Double noOfMale;
     private Double noOfFemale;
     private Date year;

    public ProgramHistory() {
    }

    public ProgramHistory(UniPrograms uniPrograms, Double noOfMale, Double noOfFemale, Date year) {
       this.uniPrograms = uniPrograms;
       this.noOfMale = noOfMale;
       this.noOfFemale = noOfFemale;
       this.year = year;
    }
   
    public Long getProgramHistoryId() {
        return this.programHistoryId;
    }
    
    public void setProgramHistoryId(Long programHistoryId) {
        this.programHistoryId = programHistoryId;
    }
    public UniPrograms getUniPrograms() {
        return this.uniPrograms;
    }
    
    public void setUniPrograms(UniPrograms uniPrograms) {
        this.uniPrograms = uniPrograms;
    }
    public Double getNoOfMale() {
        return this.noOfMale;
    }
    
    public void setNoOfMale(Double noOfMale) {
        this.noOfMale = noOfMale;
    }
    public Double getNoOfFemale() {
        return this.noOfFemale;
    }
    
    public void setNoOfFemale(Double noOfFemale) {
        this.noOfFemale = noOfFemale;
    }
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }




}


