package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Promotions generated by hbm2java
 */
public class Promotions  implements java.io.Serializable {


     private Long promotionsId;
     private EmployeeDTO employee;
     private UserDTO user;
     private DepartmentsDTO departments;
     private String promotionTitle;
     private Date dateof;
     private String promotionDetail;
     private Byte isDeleted;
     private Date createdAt;
     private String locality;
     private Long awardId;

    public Promotions() {
    }

   
   
    public Long getPromotionsId() {
        return this.promotionsId;
    }
    
    public void setPromotionsId(Long promotionsId) {
        this.promotionsId = promotionsId;
    }
    public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public DepartmentsDTO getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(DepartmentsDTO departments) {
        this.departments = departments;
    }
    public String getPromotionTitle() {
        return this.promotionTitle;
    }
    
    public void setPromotionTitle(String promotionTitle) {
        this.promotionTitle = promotionTitle;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    public String getPromotionDetail() {
        return this.promotionDetail;
    }
    
    public void setPromotionDetail(String promotionDetail) {
        this.promotionDetail = promotionDetail;
    }
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }
    public Long getAwardId() {
        return this.awardId;
    }
    
    public void setAwardId(Long awardId) {
        this.awardId = awardId;
    }




}


