package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StudentScholarships generated by hbm2java
 */
public class StudentScholarships  implements java.io.Serializable {


     private Long studentScholarshipsId;
     private Countries countries;
     private Institutions institutions;
     private Cities cities;
     private String locality;
     private Date year;
     private String nameOfSponsor;
     private Double noOfStudents;
     private String namesOfStudents;
     private String internationalUniversity;
     private String file;
     private Double noOfMale;
     private Double noOfFemale;

    public StudentScholarships() {
    }

    public StudentScholarships(Countries countries, Institutions institutions, Cities cities, String locality, Date year, String nameOfSponsor, Double noOfStudents, String namesOfStudents, String internationalUniversity, String file, Double noOfMale, Double noOfFemale) {
       this.countries = countries;
       this.institutions = institutions;
       this.cities = cities;
       this.locality = locality;
       this.year = year;
       this.nameOfSponsor = nameOfSponsor;
       this.noOfStudents = noOfStudents;
       this.namesOfStudents = namesOfStudents;
       this.internationalUniversity = internationalUniversity;
       this.file = file;
       this.noOfMale = noOfMale;
       this.noOfFemale = noOfFemale;
    }
   
    public Long getStudentScholarshipsId() {
        return this.studentScholarshipsId;
    }
    
    public void setStudentScholarshipsId(Long studentScholarshipsId) {
        this.studentScholarshipsId = studentScholarshipsId;
    }
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }
    public Institutions getInstitutions() {
        return this.institutions;
    }
    
    public void setInstitutions(Institutions institutions) {
        this.institutions = institutions;
    }
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }
    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }
    public String getNameOfSponsor() {
        return this.nameOfSponsor;
    }
    
    public void setNameOfSponsor(String nameOfSponsor) {
        this.nameOfSponsor = nameOfSponsor;
    }
    public Double getNoOfStudents() {
        return this.noOfStudents;
    }
    
    public void setNoOfStudents(Double noOfStudents) {
        this.noOfStudents = noOfStudents;
    }
    public String getNamesOfStudents() {
        return this.namesOfStudents;
    }
    
    public void setNamesOfStudents(String namesOfStudents) {
        this.namesOfStudents = namesOfStudents;
    }
    public String getInternationalUniversity() {
        return this.internationalUniversity;
    }
    
    public void setInternationalUniversity(String internationalUniversity) {
        this.internationalUniversity = internationalUniversity;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    public Double getNoOfMale() {
        return this.noOfMale;
    }
    
    public void setNoOfMale(Double noOfMale) {
        this.noOfMale = noOfMale;
    }
    public Double getNoOfFemale() {
        return this.noOfFemale;
    }
    
    public void setNoOfFemale(Double noOfFemale) {
        this.noOfFemale = noOfFemale;
    }




}


