package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA



/**
 * UniDepartments generated by hbm2java
 */
public class UniDepartments  implements java.io.Serializable {


     private Long uniDepartmentsId;
     private FacultyDTO faculty;
     private Double code;
     private String name;
     private String detail;
     private Byte isDeleted;

    public UniDepartments() {
    }

	
    public UniDepartments(FacultyDTO faculty) {
        this.faculty = faculty;
    }
    public UniDepartments(FacultyDTO faculty, Double code, String name, String detail, Byte isDeleted) {
       this.faculty = faculty;
       this.code = code;
       this.name = name;
       this.detail = detail;
       this.isDeleted = isDeleted;
    }
   
    public Long getUniDepartmentsId() {
        return this.uniDepartmentsId;
    }
    
    public void setUniDepartmentsId(Long uniDepartmentsId) {
        this.uniDepartmentsId = uniDepartmentsId;
    }
    public FacultyDTO getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(FacultyDTO faculty) {
        this.faculty = faculty;
    }
    public Double getCode() {
        return this.code;
    }
    
    public void setCode(Double code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }




}


