package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UniPrograms generated by hbm2java
 */
public class UniProgramsDTO  implements java.io.Serializable {


     private Long uniProgramsId;
     private String departmentId;
     private String code;
     private String name;
     
    
	public Long getUniProgramsId() {
		return uniProgramsId;
	}
	public void setUniProgramsId(Long uniProgramsId) {
		this.uniProgramsId = uniProgramsId;
	}
	public String getDepartmentId() {
		return departmentId;
	}
	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
     

   




}


