package pojos;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UniPrograms generated by hbm2java
 */
public class UniPrograms  implements java.io.Serializable {


     private Long uniProgramsId;
     private Departments departments;
     private Double code;
     private String name;
     private Set employeesServiceses = new HashSet(0);
     private Set accreditationses = new HashSet(0);
     private Set programHistories = new HashSet(0);

    public UniPrograms() {
    }

    public UniPrograms(Departments departments, Double code, String name, Set employeesServiceses, Set accreditationses, Set programHistories) {
       this.departments = departments;
       this.code = code;
       this.name = name;
       this.employeesServiceses = employeesServiceses;
       this.accreditationses = accreditationses;
       this.programHistories = programHistories;
    }
   
    public Long getUniProgramsId() {
        return this.uniProgramsId;
    }
    
    public void setUniProgramsId(Long uniProgramsId) {
        this.uniProgramsId = uniProgramsId;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public Double getCode() {
        return this.code;
    }
    
    public void setCode(Double code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getEmployeesServiceses() {
        return this.employeesServiceses;
    }
    
    public void setEmployeesServiceses(Set employeesServiceses) {
        this.employeesServiceses = employeesServiceses;
    }
    public Set getAccreditationses() {
        return this.accreditationses;
    }
    
    public void setAccreditationses(Set accreditationses) {
        this.accreditationses = accreditationses;
    }
    public Set getProgramHistories() {
        return this.programHistories;
    }
    
    public void setProgramHistories(Set programHistories) {
        this.programHistories = programHistories;
    }




}


