package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import com.qec.model.EmployeeModel;

/**
 * User generated by hbm2java
 */
public class UserDTO  implements java.io.Serializable {

    private Long userId;
    private EmployeeModel employeeModel;
    private Long employeeId;
    private String employeeFullName;
    private String username;
    private String oldUsername;
    private String password;
    private String role;
    private String fullName;
    DepartmentsDTO departmentsDTO = new DepartmentsDTO();
    CampusesDTO campusesDTO = new CampusesDTO();
    private Long departmentId;
    private String departmentName;
    private String campusName;
    private String email;
    private Date dateof;
    private Long campusesId;
    private Boolean isDeleted;
    private Boolean isActive;
    private String status;
       
    public Long getUserId() {
        return this.userId;
    }
    
    public Long getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	public String getEmployeeFullName() {
		return employeeFullName;
	}

	public void setEmployeeFullName(String employeeFullName) {
		this.employeeFullName = employeeFullName;
	}

	public void setUserId(Long userId) {
        this.userId = userId;
    }
    public EmployeeModel getEmployeeModel() {
		return employeeModel;
	}

	public void setEmployeeModel(EmployeeModel employeeModel) {
		this.employeeModel = employeeModel;
	}

	public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getOldUsername() {
		return oldUsername;
	}

	public void setOldUsername(String oldUsername) {
		this.oldUsername = oldUsername;
	}

	public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Long getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }
    public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
	
	public String getCampusName() {
		return campusName;
	}

	public void setCampusName(String campusName) {
		this.campusName = campusName;
	}

	public Long getCampusesId() {
		return campusesId;
	}

	public void setCampusesId(Long campusesId) {
		this.campusesId = campusesId;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public DepartmentsDTO getDepartmentsDTO() {
		return departmentsDTO;
	}

	public void setDepartmentsDTO(DepartmentsDTO departmentsDTO) {
		this.departmentsDTO = departmentsDTO;
	}

	public CampusesDTO getCampusesDTO() {
		return campusesDTO;
	}

	public void setCampusesDTO(CampusesDTO campusesDTO) {
		this.campusesDTO = campusesDTO;
	}
}


