package com.qec.dto;
// Generated Aug 19, 2017 9:08:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import com.qec.model.EmployeeModel;

/**
 * User generated by hbm2java
 */
public class UserDTO  implements java.io.Serializable {

     private Long userId;
     private EmployeeModel employeeModel;
     private Long employeeId;
     private String employeeFullName;
     private String username;
     private String password;
     private String role;
     private String fullName;
     DepartmentsDTO departmentsDTO = new DepartmentsDTO();
     CampusesDTO campusesDTO = new CampusesDTO();
     private Long departmentId;
     private String departmentName;
     //private String campusesName;
     private String email;
     private Date dateof;
     private Long campusesId;
     private Boolean isDeleted;
     private Boolean isActive;
     private String accountStatus;
    /* private Set googleCitations = new HashSet(0);
     private Set citationConferences = new HashSet(0);
     private Set accreditationses = new HashSet(0);
     private Set citationBooks = new HashSet(0);
     private Set loginsHistories = new HashSet(0);
     private Set citationOthers = new HashSet(0);
     private Set citationThesises = new HashSet(0);
     private Set promotionses = new HashSet(0);
     private Set citationJournals = new HashSet(0);
     private Set bugses = new HashSet(0);
     private Set citationChapters = new HashSet(0);
     private Set citationPatents = new HashSet(0);
     private Set eventses = new HashSet(0);
*/
   /* public UserDTO() {
    }

    public UserDTO(Employee employee, DepartmentsModel departmentsModel,String username, String password, String role, String fullName, Long departmentId, String email, Date dateof, Long campusId, Byte isDeleted, Byte isActive, Set googleCitations, Set citationConferences, Set accreditationses, Set citationBooks, Set loginsHistories, Set citationOthers, Set citationThesises, Set promotionses, Set citationJournals, Set bugses, Set citationChapters, Set citationPatents, Set eventses) {
       this.employee = employee;
       this.username = username;
       this.password = password;
       this.role = role;
       this.fullName = fullName;
       this.departmentId = departmentId;
       this.email = email;
       this.dateof = dateof;
       this.campusId = campusId;
       this.isDeleted = isDeleted;
       this.isActive = isActive;
       this.googleCitations = googleCitations;
       this.citationConferences = citationConferences;
       this.accreditationses = accreditationses;
       this.citationBooks = citationBooks;
       this.loginsHistories = loginsHistories;
       this.citationOthers = citationOthers;
       this.citationThesises = citationThesises;
       this.promotionses = promotionses;
       this.citationJournals = citationJournals;
       this.bugses = bugses;
       this.citationChapters = citationChapters;
       this.citationPatents = citationPatents;
       this.eventses = eventses;
       this.departmentsModel = departmentsModel;
    }*/
   
    public Long getUserId() {
        return this.userId;
    }
    
    public Long getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	public String getEmployeeFullName() {
		return employeeFullName;
	}

	public void setEmployeeFullName(String employeeFullName) {
		this.employeeFullName = employeeFullName;
	}

	public void setUserId(Long userId) {
        this.userId = userId;
    }
    public EmployeeModel getEmployeeModel() {
		return employeeModel;
	}

	public void setEmployeeModel(EmployeeModel employeeModel) {
		this.employeeModel = employeeModel;
	}

	public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Long getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }
    public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
	
	/*public String getCampusesName() {
		return campusesName;
	}

	public void setCampusesName(String campusesName) {
		this.campusesName = campusesName;
	}*/

	public Long getCampusesId() {
		return campusesId;
	}

	public void setCampusesId(Long campusesId) {
		this.campusesId = campusesId;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getAccountStatus() {
		return accountStatus;
	}

	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus;
	}

	public DepartmentsDTO getDepartmentsDTO() {
		return departmentsDTO;
	}

	public void setDepartmentsDTO(DepartmentsDTO departmentsDTO) {
		this.departmentsDTO = departmentsDTO;
	}

	public CampusesDTO getCampusesDTO() {
		return campusesDTO;
	}

	public void setCampusesDTO(CampusesDTO campusesDTO) {
		this.campusesDTO = campusesDTO;
	}
}


