package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accreditations generated by hbm2java
 */
@Entity
@Table(name="accreditations"
    ,catalog="qecdb"
)
public class AccreditationsModel  implements java.io.Serializable {


     private Long accreditationsId;
     private UserModel userModel;
     private FacultyModel facultyModel;
     private UniProgramsModel uniProgramsModel;
     private DepartmentsModel departmentsModel;
     private String nameOfProgram;
     private String title;
     private String locality;
     private Long accreditationCouncilId;
     private String internationalAccreditationCouncil;
     private Date year;
     private String file;
     private Date approvedDate;
     private Date validityDate;

    public AccreditationsModel() {
    }

    public AccreditationsModel(UserModel userModel, FacultyModel facultyModel, UniProgramsModel uniProgramsModel, DepartmentsModel departmentsModel, String nameOfProgram, String title, String locality, Long accreditationCouncilId, String internationalAccreditationCouncil, Date year, String file, Date approvedDate, Date validityDate) {
       this.userModel = userModel;
       this.facultyModel = facultyModel;
       this.uniProgramsModel = uniProgramsModel;
       this.departmentsModel = departmentsModel;
       this.nameOfProgram = nameOfProgram;
       this.title = title;
       this.locality = locality;
       this.accreditationCouncilId = accreditationCouncilId;
       this.internationalAccreditationCouncil = internationalAccreditationCouncil;
       this.year = year;
       this.file = file;
       this.approvedDate = approvedDate;
       this.validityDate = validityDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="accreditations_id", unique=true, nullable=false)
    public Long getAccreditationsId() {
        return this.accreditationsId;
    }
    
    public void setAccreditationsId(Long accreditationsId) {
        this.accreditationsId = accreditationsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public UserModel getUser() {
        return this.userModel;
    }
    
    public void setUser(UserModel userModel) {
        this.userModel = userModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="faculty_id")
    public FacultyModel getFaculty() {
        return this.facultyModel;
    }
    
    public void setFaculty(FacultyModel facultyModel) {
        this.facultyModel = facultyModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="program_id")
    public UniProgramsModel getUniPrograms() {
        return this.uniProgramsModel;
    }
    
    public void setUniPrograms(UniProgramsModel uniProgramsModel) {
        this.uniProgramsModel = uniProgramsModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public DepartmentsModel getDepartments() {
        return this.departmentsModel;
    }
    
    public void setDepartments(DepartmentsModel departmentsModel) {
        this.departmentsModel = departmentsModel;
    }
    
    @Column(name="name_of_program", length=250)
    public String getNameOfProgram() {
        return this.nameOfProgram;
    }
    
    public void setNameOfProgram(String nameOfProgram) {
        this.nameOfProgram = nameOfProgram;
    }
    
    @Column(name="title", length=250)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="locality", length=16)
    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }
    
    @Column(name="accreditation_council_id")
    public Long getAccreditationCouncilId() {
        return this.accreditationCouncilId;
    }
    
    public void setAccreditationCouncilId(Long accreditationCouncilId) {
        this.accreditationCouncilId = accreditationCouncilId;
    }
    
    @Column(name="international_accreditation_council", length=250)
    public String getInternationalAccreditationCouncil() {
        return this.internationalAccreditationCouncil;
    }
    
    public void setInternationalAccreditationCouncil(String internationalAccreditationCouncil) {
        this.internationalAccreditationCouncil = internationalAccreditationCouncil;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year", length=0)
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }
    
    @Column(name="file", length=250)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="approved_date", length=10)
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="validity_date", length=10)
    public Date getValidityDate() {
        return this.validityDate;
    }
    
    public void setValidityDate(Date validityDate) {
        this.validityDate = validityDate;
    }




}


