package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AccreditationCouncilid generated by hbm2java
 */
@Entity
@Table(name="accreditation_councilid")
public class AccreditationCouncilModel  implements java.io.Serializable {


     private Long accreditationCouncilId;
     private String name;

    public AccreditationCouncilModel() {
    }

    public AccreditationCouncilModel(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="accreditation_council_id", unique=true, nullable=false)
    public Long getAccreditationCouncilId() {
        return this.accreditationCouncilId;
    }
    
    public void setAccreditationCouncilId(Long accreditationCouncilId) {
        this.accreditationCouncilId = accreditationCouncilId;
    }
    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


