package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CitationPatent generated by hbm2java
 */
@Entity
@Table(name="citation_patent")
public class CitationPatentModel extends Model  implements java.io.Serializable {


     private Long citationPatentId;
     private EmployeeModel employeeModel;
     private UserModel userModel;
     private String title;
     private String url;
     private String inventors;
     private Date publicationDate;
     private String patentOffice;
     private String patentNumber;
     private String applicationNumber;
     private String description;
   
     @Id @GeneratedValue(strategy=IDENTITY)
     @Column(name="citation_patent_id", unique=true, nullable=false)
     public Long getCitationPatentId() {
        return this.citationPatentId;
     }
    
     public void setCitationPatentId(Long citationPatentId) {
        this.citationPatentId = citationPatentId;
     }

     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="employee_id")
     public EmployeeModel getEmployeeModel() {
        return this.employeeModel;
     }
    
     public void setEmployeeModel(EmployeeModel employeeModel) {
    	 this.employeeModel = employeeModel;
     }

     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="user_id")
     public UserModel getUser() {
        return this.userModel;
     }
    
     public void setUser(UserModel userModel) {
        this.userModel = userModel;
     }
    
     @Column(name="title", length=65535)
     public String getTitle() {
        return this.title;
     }
    
     public void setTitle(String title) {
        this.title = title;
     }
    
     @Column(name="url", length=65535)
     public String getUrl() {
        return this.url;
     }
    
     public void setUrl(String url) {
        this.url = url;
     }
    
     @Column(name="inventors", length=65535)
     public String getInventors() {
        return this.inventors;
     }
    
     public void setInventors(String inventors) {
        this.inventors = inventors;
     }
    
     @Temporal(TemporalType.DATE)
     @Column(name="publication_date", length=10)
     public Date getPublicationDate() {
        return this.publicationDate;
     }
    
     public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
     }
    
     @Column(name="patent_office", length=100)
     public String getPatentOffice() {
        return this.patentOffice;
     }
    
     public void setPatentOffice(String patentOffice) {
        this.patentOffice = patentOffice;
     }
    
     @Column(name="patent_number", length=100)
     public String getPatentNumber() {
        return this.patentNumber;
     }
    
     public void setPatentNumber(String patentNumber) {
        this.patentNumber = patentNumber;
     }
    
     @Column(name="application_number", length=100)
     public String getApplicationNumber() {
        return this.applicationNumber;
     }
    
     public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber;
     }
    
     @Column(name="description", length=65535)
     public String getDescription() {
        return this.description;
     }
    
     public void setDescription(String description) {
        this.description = description;
     }
}


