package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GoogleCitation generated by hbm2java
 */
@Entity
@Table(name="google_citation"
    ,catalog="qecdb"
)
public class CitationGoogleModel extends Model implements java.io.Serializable {

     private Long citationGoogleId;
     private EmployeeModel employeeModel;
     private UserModel userModel;
     private String url;
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="google_citation_id", unique=true, nullable=false)
    public Long getCitationGoogleId() {
        return this.citationGoogleId;
    }
    
    public void setCitationGoogleId(Long citationGoogleId) {
        this.citationGoogleId = citationGoogleId;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployeeModel() {
        return this.employeeModel;
    }
    
    public void setEmployeeModel(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public UserModel getUser() {
        return this.userModel;
    }
    
    public void setUser(UserModel userModel) {
        this.userModel = userModel;
    }
    
    @Column(name="url", length=65535)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
}