package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name="cities"
    ,catalog="qecdb"
)
public class CitiesModel  implements java.io.Serializable {

    private Long citiesId;
    private String cityName;
    private String province;
    private String abbrivation;
      
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="cities_id", unique=true, nullable=false)
    public Long getCitiesId() {
        return this.citiesId;
    }
    
    public void setCitiesId(Long citiesId) {
        this.citiesId = citiesId;
    }
    
    @Column(name="city_name", length=250)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    
    @Column(name="province", length=11)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    
    @Column(name="abbrivation", length=250)
    public String getAbbrivation() {
        return this.abbrivation;
    }
    
    public void setAbbrivation(String abbrivation) {
        this.abbrivation = abbrivation;
    }
}