package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name="countries"
    ,catalog="qecdb"
)
public class CountriesModel  implements java.io.Serializable {


	private Long countriesId;
    private String countryName;

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="countries_id", unique=true, nullable=false)
    public Long getCountriesId() {
        return this.countriesId;
    }
    
    public void setCountriesId(Long countriesId) {
        this.countriesId = countriesId;
    }
    
    @Column(name="country_name", length=100)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
}


