package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name="countries"
    ,catalog="qecdb"
)
public class CountriesModel  implements java.io.Serializable {


     private Long countriesId;
     private String countryName;
     private Set<EmpTrainingsModel> empTrainingses = new HashSet<EmpTrainingsModel>(0);
     private Set<StudentScholarshipsModel> studentScholarshipses = new HashSet<StudentScholarshipsModel>(0);
     private Set<EmpTravelgrandsModel> empTravelgrandses = new HashSet<EmpTravelgrandsModel>(0);

    public CountriesModel() {
    }

    public CountriesModel(String countryName, Set<EmpTrainingsModel> empTrainingses, Set<StudentScholarshipsModel> studentScholarshipses, Set<EmpTravelgrandsModel> empTravelgrandses) {
       this.countryName = countryName;
       this.empTrainingses = empTrainingses;
       this.studentScholarshipses = studentScholarshipses;
       this.empTravelgrandses = empTravelgrandses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="countries_id", unique=true, nullable=false)
    public Long getCountriesId() {
        return this.countriesId;
    }
    
    public void setCountriesId(Long countriesId) {
        this.countriesId = countriesId;
    }
    
    @Column(name="country_name", length=100)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="countries")
    public Set<EmpTrainingsModel> getEmpTrainingses() {
        return this.empTrainingses;
    }
    
    public void setEmpTrainingses(Set<EmpTrainingsModel> empTrainingses) {
        this.empTrainingses = empTrainingses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="countries")
    public Set<StudentScholarshipsModel> getStudentScholarshipses() {
        return this.studentScholarshipses;
    }
    
    public void setStudentScholarshipses(Set<StudentScholarshipsModel> studentScholarshipses) {
        this.studentScholarshipses = studentScholarshipses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="countries")
    public Set<EmpTravelgrandsModel> getEmpTravelgrandses() {
        return this.empTravelgrandses;
    }
    
    public void setEmpTravelgrandses(Set<EmpTravelgrandsModel> empTravelgrandses) {
        this.empTravelgrandses = empTravelgrandses;
    }




}


