package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpCommunityservices generated by hbm2java
 */
@Entity
@Table(name="emp_communityservices"
    ,catalog="qecdb"
)
public class EmpCommunityservicesModel  implements java.io.Serializable {


     private Long empCommunityservicesId;
     private EmployeeModel employeeModel;
     private String name;
     private Date dateof;
     private String place;
     private String file;

    public EmpCommunityservicesModel() {
    }

    public EmpCommunityservicesModel(EmployeeModel employeeModel, String name, Date dateof, String place, String file) {
       this.employeeModel = employeeModel;
       this.name = name;
       this.dateof = dateof;
       this.place = place;
       this.file = file;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="emp_communityservices_id", unique=true, nullable=false)
    public Long getEmpCommunityservicesId() {
        return this.empCommunityservicesId;
    }
    
    public void setEmpCommunityservicesId(Long empCommunityservicesId) {
        this.empCommunityservicesId = empCommunityservicesId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployee() {
        return this.employeeModel;
    }
    
    public void setEmployee(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }
    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateof", length=10)
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    
    @Column(name="place", length=250)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    
    @Column(name="file", length=250)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }




}


