package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpPhdstrategy generated by hbm2java
 */
@Entity
@Table(name="employee_mphil_phd_students")
public class EmployeeMphilPhdStudentsModel extends Model  implements java.io.Serializable {


     private Long employeeMphilPhdStudentsId;
     private EmployeeModel employee;
     private DepartmentsModel departments;
     private String studentName;
     private String dtype;
     private Double noOfStudents;
     private Date startDate;
     private Date registrationDate;
     private Double studentId;
     private String file;
     private String approvedTopic;

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="employee_mphil_phd_students_id", unique=true, nullable=false)
    public Long getEmployeeMphilPhdStudentsId() {
        return this.employeeMphilPhdStudentsId;
    }
    
    public void setEmployeeMphilPhdStudentsId(Long employeeMphilPhdStudentsId) {
        this.employeeMphilPhdStudentsId = employeeMphilPhdStudentsId;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeModel employee) {
        this.employee = employee;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public DepartmentsModel getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(DepartmentsModel departments) {
        this.departments = departments;
    }
    
    @Column(name="student_name", length=250)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    
    @Column(name="dtype", length=6)
    public String getDtype() {
        return this.dtype;
    }
    
    public void setDtype(String dtype) {
        this.dtype = dtype;
    }
    
    @Column(name="no_of_students", precision=22, scale=0)
    public Double getNoOfStudents() {
        return this.noOfStudents;
    }
    
    public void setNoOfStudents(Double noOfStudents) {
        this.noOfStudents = noOfStudents;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="registration_date", length=10)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    
    @Column(name="student_id", precision=22, scale=0)
    public Double getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Double studentId) {
        this.studentId = studentId;
    }
    
    @Column(name="file", length=250)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    
    @Column(name="approved_topic", length=250)
    public String getApprovedTopic() {
        return this.approvedTopic;
    }
    
    public void setApprovedTopic(String approvedTopic) {
        this.approvedTopic = approvedTopic;
    }
}


