package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeesServices generated by hbm2java
 */
@Entity
@Table(name="employees_services"
    ,catalog="qecdb"
)
public class EmployeesServicesModel  implements java.io.Serializable {


     private Long employeesServicesId;
     private UniProgramsModel uniProgramsModel;
     private EmployeeModel employeeModel;
     private FacultyModel facultyModel;
     private DepartmentsModel departmentsModel;
     private String department;
     private String empType;
     private String postHeld;
     private String jobStatus;
     private String natureOfJob;
     private Date postStartDate;
     private Date postEndDate;
     private String jobDuties;
     private String tcategory;
     private String grade;
     private Short scale;
     private Byte currentWorking;

    public EmployeesServicesModel() {
    }

	
    public EmployeesServicesModel(FacultyModel facultyModel, String empType) {
        this.facultyModel = facultyModel;
        this.empType = empType;
    }
    public EmployeesServicesModel(UniProgramsModel uniProgramsModel, EmployeeModel employeeModel, FacultyModel facultyModel, DepartmentsModel departmentsModel, String department, String empType, String postHeld, String jobStatus, String natureOfJob, Date postStartDate, Date postEndDate, String jobDuties, String tcategory, String grade, Short scale, Byte currentWorking) {
       this.uniProgramsModel = uniProgramsModel;
       this.employeeModel = employeeModel;
       this.facultyModel = facultyModel;
       this.departmentsModel = departmentsModel;
       this.department = department;
       this.empType = empType;
       this.postHeld = postHeld;
       this.jobStatus = jobStatus;
       this.natureOfJob = natureOfJob;
       this.postStartDate = postStartDate;
       this.postEndDate = postEndDate;
       this.jobDuties = jobDuties;
       this.tcategory = tcategory;
       this.grade = grade;
       this.scale = scale;
       this.currentWorking = currentWorking;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="employees_services_id", unique=true, nullable=false)
    public Long getEmployeesServicesId() {
        return this.employeesServicesId;
    }
    
    public void setEmployeesServicesId(Long employeesServicesId) {
        this.employeesServicesId = employeesServicesId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uni_program_id")
    public UniProgramsModel getUniPrograms() {
        return this.uniProgramsModel;
    }
    
    public void setUniPrograms(UniProgramsModel uniProgramsModel) {
        this.uniProgramsModel = uniProgramsModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployee() {
        return this.employeeModel;
    }
    
    public void setEmployee(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="faculty_id", nullable=false)
    public FacultyModel getFaculty() {
        return this.facultyModel;
    }
    
    public void setFaculty(FacultyModel facultyModel) {
        this.facultyModel = facultyModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public DepartmentsModel getDepartments() {
        return this.departmentsModel;
    }
    
    public void setDepartments(DepartmentsModel departmentsModel) {
        this.departmentsModel = departmentsModel;
    }
    
    @Column(name="department", length=250)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    
    @Column(name="emp_type", nullable=false, length=11)
    public String getEmpType() {
        return this.empType;
    }
    
    public void setEmpType(String empType) {
        this.empType = empType;
    }
    
    @Column(name="post_held", length=250)
    public String getPostHeld() {
        return this.postHeld;
    }
    
    public void setPostHeld(String postHeld) {
        this.postHeld = postHeld;
    }
    
    @Column(name="job_status", length=250)
    public String getJobStatus() {
        return this.jobStatus;
    }
    
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus;
    }
    
    @Column(name="nature_of_job", length=250)
    public String getNatureOfJob() {
        return this.natureOfJob;
    }
    
    public void setNatureOfJob(String natureOfJob) {
        this.natureOfJob = natureOfJob;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="post_start_date", length=10)
    public Date getPostStartDate() {
        return this.postStartDate;
    }
    
    public void setPostStartDate(Date postStartDate) {
        this.postStartDate = postStartDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="post_end_date", length=10)
    public Date getPostEndDate() {
        return this.postEndDate;
    }
    
    public void setPostEndDate(Date postEndDate) {
        this.postEndDate = postEndDate;
    }
    
    @Column(name="job_duties", length=65535)
    public String getJobDuties() {
        return this.jobDuties;
    }
    
    public void setJobDuties(String jobDuties) {
        this.jobDuties = jobDuties;
    }
    
    @Column(name="tcategory", length=21)
    public String getTcategory() {
        return this.tcategory;
    }
    
    public void setTcategory(String tcategory) {
        this.tcategory = tcategory;
    }
    
    @Column(name="grade", length=4)
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    
    @Column(name="scale")
    public Short getScale() {
        return this.scale;
    }
    
    public void setScale(Short scale) {
        this.scale = scale;
    }
    
    @Column(name="current_working")
    public Byte getCurrentWorking() {
        return this.currentWorking;
    }
    
    public void setCurrentWorking(Byte currentWorking) {
        this.currentWorking = currentWorking;
    }




}


