package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeesEducation generated by hbm2java
 */
@Entity
@Table(name="employees_education")
public class EmployeesEducationModel  implements java.io.Serializable {


     private Long employeesEducationId;
     private EmployeeModel employeeModel;
     private CitiesModel citiesModel;
     private String degreeLevel;
     private String examinationPassed;
     private Date resultDate;
     private String university;
     private String otherUniversity;
     private String grade;
     private String subject1;
     private String subject2;
     private String subject3;

    public EmployeesEducationModel() {
    }

    public EmployeesEducationModel(EmployeeModel employeeModel, CitiesModel citiesModel, String degreeLevel, String examinationPassed, Date resultDate, String university, String otherUniversity, String grade, String subject1, String subject2, String subject3) {
       this.employeeModel = employeeModel;
       this.citiesModel = citiesModel;
       this.degreeLevel = degreeLevel;
       this.examinationPassed = examinationPassed;
       this.resultDate = resultDate;
       this.university = university;
       this.otherUniversity = otherUniversity;
       this.grade = grade;
       this.subject1 = subject1;
       this.subject2 = subject2;
       this.subject3 = subject3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="employees_education_id", unique=true, nullable=false)
    public Long getEmployeesEducationId() {
        return this.employeesEducationId;
    }
    
    public void setEmployeesEducationId(Long employeesEducationId) {
        this.employeesEducationId = employeesEducationId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployee() {
        return this.employeeModel;
    }
    
    public void setEmployee(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cities_id")
    public CitiesModel getCities() {
        return this.citiesModel;
    }
    
    public void setCities(CitiesModel citiesModel) {
        this.citiesModel = citiesModel;
    }
    
    @Column(name="degree_level", length=250)
    public String getDegreeLevel() {
        return this.degreeLevel;
    }
    
    public void setDegreeLevel(String degreeLevel) {
        this.degreeLevel = degreeLevel;
    }
    
    @Column(name="examination_passed", length=25)
    public String getExaminationPassed() {
        return this.examinationPassed;
    }
    
    public void setExaminationPassed(String examinationPassed) {
        this.examinationPassed = examinationPassed;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="result_date", length=0)
    public Date getResultDate() {
        return this.resultDate;
    }
    
    public void setResultDate(Date resultDate) {
        this.resultDate = resultDate;
    }
    
    @Column(name="university", length=250)
    public String getUniversity() {
        return this.university;
    }
    
    public void setUniversity(String university) {
        this.university = university;
    }
    
    @Column(name="other_university", length=250)
    public String getOtherUniversity() {
        return this.otherUniversity;
    }
    
    public void setOtherUniversity(String otherUniversity) {
        this.otherUniversity = otherUniversity;
    }
    
    @Column(name="grade", length=250)
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    
    @Column(name="subject1", length=250)
    public String getSubject1() {
        return this.subject1;
    }
    
    public void setSubject1(String subject1) {
        this.subject1 = subject1;
    }
    
    @Column(name="subject2", length=250)
    public String getSubject2() {
        return this.subject2;
    }
    
    public void setSubject2(String subject2) {
        this.subject2 = subject2;
    }
    
    @Column(name="subject3", length=250)
    public String getSubject3() {
        return this.subject3;
    }
    
    public void setSubject3(String subject3) {
        this.subject3 = subject3;
    }




}


