package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="qecdb"
)
public class EmployeeModel extends Model  implements java.io.Serializable {

     private Long employeeId;
     private DepartmentsModel departmentsModel;
     private String title;
     private String fullName;
     private String surname;
     private String cast;
     private String maritalStatus;
     private String fatherName;
     private String husbandName;
     private String email;
     private String postalAddress;
     private String presentAddress;
     private String nic;
     private Date dob;
     private String gender;
     private String mobile;
     private String phone;
     private String religion;
     private String country;
     private String imgPath;
     private Boolean isDeleted;

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="employee_id", unique=true, nullable=false)
    public Long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public DepartmentsModel getDepartmentsModel() {
        return this.departmentsModel;
    }
    
    public void setDepartmentsModel(DepartmentsModel departmentsModel) {
        this.departmentsModel = departmentsModel;
    }
    
    @Column(name="title", length=3)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="full_name", length=250)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    @Column(name="surname", length=250)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    @Column(name="cast", length=250)
    public String getCast() {
        return this.cast;
    }
    
    public void setCast(String cast) {
        this.cast = cast;
    }
    
    @Column(name="marital_status", length=9)
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    
    @Column(name="father_name", length=250)
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    
    @Column(name="husband_name", length=250)
    public String getHusbandName() {
        return this.husbandName;
    }
    
    public void setHusbandName(String husbandName) {
        this.husbandName = husbandName;
    }
    
    @Column(name="email", length=250)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="postal_address", length=65535)
    public String getPostalAddress() {
        return this.postalAddress;
    }
    
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress;
    }
    
    @Column(name="present_address", length=65535)
    public String getPresentAddress() {
        return this.presentAddress;
    }
    
    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }
    
    @Column(name="nic", length=100)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    
    @Column(name="gender", length=11)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="mobile", length=100)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="phone", length=100)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="religion", length=9)
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    
    @Column(name="country", length=250)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="img_path", length=250)
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    
    @Column(name="is_deleted")
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

}


