package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpTrainings generated by hbm2java
 */
@Entity
@Table(name="emp_trainings"
    ,catalog="qecdb"
)
public class EmployeeTrainingModel extends Model implements java.io.Serializable {

     private Long empTrainingsId;
     private EmployeeModel employeeModel;
     private CountriesModel countriesModel;
     private CitiesModel citiesModel;
     private String name;
     private String place;
     private String file;
     private String locality;
     private String instituteName;
     private String trainingCondition;
     private Date dateof;
     private String fundingDetail;

  
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="emp_trainings_id", unique=true, nullable=false)
    public Long getEmpTrainingsId() {
        return this.empTrainingsId;
    }
    
    public void setEmpTrainingsId(Long empTrainingsId) {
        this.empTrainingsId = empTrainingsId;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployeeModel() {
        return this.employeeModel;
    }
    
    public void setEmployeeModel(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="countries_id")
    public CountriesModel getCountriesModel() {
        return this.countriesModel;
    }
    
    public void setCountriesModel(CountriesModel countriesModel) {
        this.countriesModel = countriesModel;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cities_id")
    public CitiesModel getCitiesModel() {
        return this.citiesModel;
    }
    
    public void setCitiesModel(CitiesModel citiesModel) {
        this.citiesModel = citiesModel;
    }
    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="place", length=250)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    
    @Column(name="file", length=250)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    
    @Column(name="locality", length=13)
    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }
    
    @Column(name="institute_name", length=250)
    public String getInstituteName() {
        return this.instituteName;
    }
    
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName;
    }
    
    @Column(name="training_condition", length=10)
    public String getTrainingCondition() {
        return this.trainingCondition;
    }
    
    public void setTrainingCondition(String trainingCondition) {
        this.trainingCondition = trainingCondition;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateof", length=10)
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    
    @Column(name="funding_detail", length=65535)
    public String getFundingDetail() {
        return this.fundingDetail;
    }
    
    public void setFundingDetail(String fundingDetail) {
        this.fundingDetail = fundingDetail;
    }




}


