package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpPhdstrategy generated by hbm2java
 */
@Entity
@Table(name="emp_phdstrategy")
public class EmpPhdstrategyModel  implements java.io.Serializable {


     private Long empPhdstrategyId;
     private EmployeeModel employeeModel;
     private DepartmentsModel departmentsModel;
     private String studentName;
     private String dtype;
     private Double noOfStudents;
     private Date startDate;
     private Date regDate;
     private Double rollNo;
     private String file;
     private String topic;

    public EmpPhdstrategyModel() {
    }

    public EmpPhdstrategyModel(EmployeeModel employeeModel, DepartmentsModel departmentsModel, String studentName, String dtype, Double noOfStudents, Date startDate, Date regDate, Double rollNo, String file, String topic) {
       this.employeeModel = employeeModel;
       this.departmentsModel = departmentsModel;
       this.studentName = studentName;
       this.dtype = dtype;
       this.noOfStudents = noOfStudents;
       this.startDate = startDate;
       this.regDate = regDate;
       this.rollNo = rollNo;
       this.file = file;
       this.topic = topic;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="emp_phdstrategy_id", unique=true, nullable=false)
    public Long getEmpPhdstrategyId() {
        return this.empPhdstrategyId;
    }
    
    public void setEmpPhdstrategyId(Long empPhdstrategyId) {
        this.empPhdstrategyId = empPhdstrategyId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployee() {
        return this.employeeModel;
    }
    
    public void setEmployee(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public DepartmentsModel getDepartments() {
        return this.departmentsModel;
    }
    
    public void setDepartments(DepartmentsModel departmentsModel) {
        this.departmentsModel = departmentsModel;
    }
    
    @Column(name="student_name", length=250)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    
    @Column(name="dtype", length=6)
    public String getDtype() {
        return this.dtype;
    }
    
    public void setDtype(String dtype) {
        this.dtype = dtype;
    }
    
    @Column(name="no_of_students", precision=22, scale=0)
    public Double getNoOfStudents() {
        return this.noOfStudents;
    }
    
    public void setNoOfStudents(Double noOfStudents) {
        this.noOfStudents = noOfStudents;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="reg_date", length=10)
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    
    @Column(name="roll_no", precision=22, scale=0)
    public Double getRollNo() {
        return this.rollNo;
    }
    
    public void setRollNo(Double rollNo) {
        this.rollNo = rollNo;
    }
    
    @Column(name="file", length=250)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    
    @Column(name="topic", length=250)
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }




}


