package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpTravelgrands generated by hbm2java
 */
@Entity
@Table(name="emp_travelgrands"
    ,catalog="qecdb"
)
public class EmpTravelgrandsModel  implements java.io.Serializable {


     private Long empTravelgrandsId;
     private EmployeeModel employeeModel;
     private CountriesModel countriesModel;
     private CitiesModel citiesModel;
     private String nature;
     private Double amount;
     private Date durationStart;
     private Date durationEnd;
     private String locType;
     private String file;
     private String nameOfProject;
     private String grandType;
     private String fundingAgency;
     private Date approvalDate;

  
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="emp_travelgrands_id", unique=true, nullable=false)
    public Long getEmpTravelgrandsId() {
        return this.empTravelgrandsId;
    }
    
    public void setEmpTravelgrandsId(Long empTravelgrandsId) {
        this.empTravelgrandsId = empTravelgrandsId;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployeeModel() {
        return this.employeeModel;
    }
    
    public void setEmployeeModel(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="countries_id")
    public CountriesModel getCountriesModel() {
        return this.countriesModel;
    }
    
    public void setCountriesModel(CountriesModel countriesModel) {
        this.countriesModel = countriesModel;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cities_id")
    public CitiesModel getCitiesModel() {
        return this.citiesModel;
    }
    
    public void setCitiesModel(CitiesModel citiesModel) {
        this.citiesModel = citiesModel;
    }
    
    @Column(name="nature", length=250)
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }
    
    @Column(name="amount", precision=22, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="duration_start", length=10)
    public Date getDurationStart() {
        return this.durationStart;
    }
    
    public void setDurationStart(Date durationStart) {
        this.durationStart = durationStart;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="duration_end", length=10)
    public Date getDurationEnd() {
        return this.durationEnd;
    }
    
    public void setDurationEnd(Date durationEnd) {
        this.durationEnd = durationEnd;
    }
    
    @Column(name="loc_type", length=13)
    public String getLocType() {
        return this.locType;
    }
    
    public void setLocType(String locType) {
        this.locType = locType;
    }
    
    @Column(name="file", length=250)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    
    @Column(name="name_of_project", length=250)
    public String getNameOfProject() {
        return this.nameOfProject;
    }
    
    public void setNameOfProject(String nameOfProject) {
        this.nameOfProject = nameOfProject;
    }
    
    @Column(name="grand_type", length=9)
    public String getGrandType() {
        return this.grandType;
    }
    
    public void setGrandType(String grandType) {
        this.grandType = grandType;
    }
    
    @Column(name="funding_agency", length=250)
    public String getFundingAgency() {
        return this.fundingAgency;
    }
    
    public void setFundingAgency(String fundingAgency) {
        this.fundingAgency = fundingAgency;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="approval_date", length=10)
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }

}


