package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventBookings generated by hbm2java
 */
@Entity
@Table(name="event_bookings"
    ,catalog="qecdb"
)
public class EventBookingsModel  implements java.io.Serializable {


     private Long id;
     private Long eventId;
     private String name;
     private String email;
     private Date dateof;
     private Byte isApproved;

    public EventBookingsModel() {
    }

    public EventBookingsModel(Long eventId, String name, String email, Date dateof, Byte isApproved) {
       this.eventId = eventId;
       this.name = name;
       this.email = email;
       this.dateof = dateof;
       this.isApproved = isApproved;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="event_id")
    public Long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }
    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="email", length=250)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateof", length=10)
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    
    @Column(name="is_approved")
    public Byte getIsApproved() {
        return this.isApproved;
    }
    
    public void setIsApproved(Byte isApproved) {
        this.isApproved = isApproved;
    }




}


