package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Faculty generated by hbm2java
 */
@Entity
@Table(name="faculty"
    ,catalog="qecdb"
)
public class FacultyModel  implements java.io.Serializable {


     private Long facultyId;
     private String facultyName;
     private Set<UniDepartmentsModel> uniDepartmentses = new HashSet<UniDepartmentsModel>(0);
     private Set<AccreditationsModel> accreditationses = new HashSet<AccreditationsModel>(0);
     private Set<EmployeesServicesModel> employeesServiceses = new HashSet<EmployeesServicesModel>(0);

    public FacultyModel() {
    }

	
    public FacultyModel(String facultyName) {
        this.facultyName = facultyName;
    }
    public FacultyModel(String facultyName, Set<UniDepartmentsModel> uniDepartmentses, Set<AccreditationsModel> accreditationses, Set<EmployeesServicesModel> employeesServiceses) {
       this.facultyName = facultyName;
       this.uniDepartmentses = uniDepartmentses;
       this.accreditationses = accreditationses;
       this.employeesServiceses = employeesServiceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="faculty_id", unique=true, nullable=false)
    public Long getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }
    
    @Column(name="faculty_name", nullable=false, length=200)
    public String getFacultyName() {
        return this.facultyName;
    }
    
    public void setFacultyName(String facultyName) {
        this.facultyName = facultyName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="faculty")
    public Set<UniDepartmentsModel> getUniDepartmentses() {
        return this.uniDepartmentses;
    }
    
    public void setUniDepartmentses(Set<UniDepartmentsModel> uniDepartmentses) {
        this.uniDepartmentses = uniDepartmentses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="faculty")
    public Set<AccreditationsModel> getAccreditationses() {
        return this.accreditationses;
    }
    
    public void setAccreditationses(Set<AccreditationsModel> accreditationses) {
        this.accreditationses = accreditationses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="faculty")
    public Set<EmployeesServicesModel> getEmployeesServiceses() {
        return this.employeesServiceses;
    }
    
    public void setEmployeesServiceses(Set<EmployeesServicesModel> employeesServiceses) {
        this.employeesServiceses = employeesServiceses;
    }




}


