package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name="images"
    ,catalog="qecdb"
)
public class ImagesModel  implements java.io.Serializable {


     private Long imagesId;
     private EventsModel eventsModel;
     private String imageName;
     private Long promotionId;

    public ImagesModel() {
    }

    public ImagesModel(EventsModel eventsModel, String imageName, Long promotionId) {
       this.eventsModel = eventsModel;
       this.imageName = imageName;
       this.promotionId = promotionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="images_id", unique=true, nullable=false)
    public Long getImagesId() {
        return this.imagesId;
    }
    
    public void setImagesId(Long imagesId) {
        this.imagesId = imagesId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="events_id")
    public EventsModel getEvents() {
        return this.eventsModel;
    }
    
    public void setEvents(EventsModel eventsModel) {
        this.eventsModel = eventsModel;
    }
    
    @Column(name="image_name", length=250)
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    
    @Column(name="promotion_id")
    public Long getPromotionId() {
        return this.promotionId;
    }
    
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }




}


