package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Institutions generated by hbm2java
 */
@Entity
@Table(name="institutions"
    ,catalog="qecdb"
)
public class InstitutionsModel  implements java.io.Serializable {


     private Long institutionsId;
     private String institutionName;
     private Byte isUniversity;
     private Set<StudentScholarshipsModel> studentScholarshipses = new HashSet<StudentScholarshipsModel>(0);

    public InstitutionsModel() {
    }

    public InstitutionsModel(String institutionName, Byte isUniversity, Set<StudentScholarshipsModel> studentScholarshipses) {
       this.institutionName = institutionName;
       this.isUniversity = isUniversity;
       this.studentScholarshipses = studentScholarshipses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="institutions_id", unique=true, nullable=false)
    public Long getInstitutionsId() {
        return this.institutionsId;
    }
    
    public void setInstitutionsId(Long institutionsId) {
        this.institutionsId = institutionsId;
    }
    
    @Column(name="institution_name", length=250)
    public String getInstitutionName() {
        return this.institutionName;
    }
    
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }
    
    @Column(name="is_university")
    public Byte getIsUniversity() {
        return this.isUniversity;
    }
    
    public void setIsUniversity(Byte isUniversity) {
        this.isUniversity = isUniversity;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="institutions")
    public Set<StudentScholarshipsModel> getStudentScholarshipses() {
        return this.studentScholarshipses;
    }
    
    public void setStudentScholarshipses(Set<StudentScholarshipsModel> studentScholarshipses) {
        this.studentScholarshipses = studentScholarshipses;
    }




}


