package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginsHistory generated by hbm2java
 */
@Entity
@Table(name="logins_history"
    ,catalog="qecdb"
)
public class LoginsHistoryModel  implements java.io.Serializable {


     private Long loginsHistoryId;
     private UserModel userModel;
     private Date dateof;
     private Date startTime;
     private Date endTime;

    public LoginsHistoryModel() {
    }

    public LoginsHistoryModel(UserModel userModel, Date dateof, Date startTime, Date endTime) {
       this.userModel = userModel;
       this.dateof = dateof;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="logins_history_id", unique=true, nullable=false)
    public Long getLoginsHistoryId() {
        return this.loginsHistoryId;
    }
    
    public void setLoginsHistoryId(Long loginsHistoryId) {
        this.loginsHistoryId = loginsHistoryId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public UserModel getUser() {
        return this.userModel;
    }
    
    public void setUser(UserModel userModel) {
        this.userModel = userModel;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateof", length=10)
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="start_time", length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="end_time", length=8)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


