package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProgramHistory generated by hbm2java
 */
@Entity
@Table(name="program_history"
    ,catalog="qecdb"
)
public class ProgramHistoryModel  implements java.io.Serializable {


     private Long programHistoryId;
     private UniProgramsModel uniProgramsModel;
     private Double noOfMale;
     private Double noOfFemale;
     private Date year;

    public ProgramHistoryModel() {
    }

    public ProgramHistoryModel(UniProgramsModel uniProgramsModel, Double noOfMale, Double noOfFemale, Date year) {
       this.uniProgramsModel = uniProgramsModel;
       this.noOfMale = noOfMale;
       this.noOfFemale = noOfFemale;
       this.year = year;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="program_history_id", unique=true, nullable=false)
    public Long getProgramHistoryId() {
        return this.programHistoryId;
    }
    
    public void setProgramHistoryId(Long programHistoryId) {
        this.programHistoryId = programHistoryId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uni_programs_id")
    public UniProgramsModel getUniPrograms() {
        return this.uniProgramsModel;
    }
    
    public void setUniPrograms(UniProgramsModel uniProgramsModel) {
        this.uniProgramsModel = uniProgramsModel;
    }
    
    @Column(name="no_of_male", precision=22, scale=0)
    public Double getNoOfMale() {
        return this.noOfMale;
    }
    
    public void setNoOfMale(Double noOfMale) {
        this.noOfMale = noOfMale;
    }
    
    @Column(name="no_of_female", precision=22, scale=0)
    public Double getNoOfFemale() {
        return this.noOfFemale;
    }
    
    public void setNoOfFemale(Double noOfFemale) {
        this.noOfFemale = noOfFemale;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year", length=0)
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }




}


