package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotions generated by hbm2java
 */
@Entity
@Table(name="promotions"
    ,catalog="qecdb"
)
public class PromotionsModel  implements java.io.Serializable {


     private Long promotionsId;
     private EmployeeModel employeeModel;
     private UserModel userModel;
     private DepartmentsModel departmentsModel;
     private String promotionTitle;
     private Date dateof;
     private String promotionDetail;
     private Byte isDeleted;
     private Date createdAt;
     private String locality;
     private Long awardId;

    public PromotionsModel() {
    }

    public PromotionsModel(EmployeeModel employeeModel, UserModel userModel, DepartmentsModel departmentsModel, String promotionTitle, Date dateof, String promotionDetail, Byte isDeleted, Date createdAt, String locality, Long awardId) {
       this.employeeModel = employeeModel;
       this.userModel = userModel;
       this.departmentsModel = departmentsModel;
       this.promotionTitle = promotionTitle;
       this.dateof = dateof;
       this.promotionDetail = promotionDetail;
       this.isDeleted = isDeleted;
       this.createdAt = createdAt;
       this.locality = locality;
       this.awardId = awardId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="promotions_id", unique=true, nullable=false)
    public Long getPromotionsId() {
        return this.promotionsId;
    }
    
    public void setPromotionsId(Long promotionsId) {
        this.promotionsId = promotionsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public EmployeeModel getEmployee() {
        return this.employeeModel;
    }
    
    public void setEmployee(EmployeeModel employeeModel) {
        this.employeeModel = employeeModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public UserModel getUser() {
        return this.userModel;
    }
    
    public void setUser(UserModel userModel) {
        this.userModel = userModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public DepartmentsModel getDepartments() {
        return this.departmentsModel;
    }
    
    public void setDepartments(DepartmentsModel departmentsModel) {
        this.departmentsModel = departmentsModel;
    }
    
    @Column(name="promotion_title", length=250)
    public String getPromotionTitle() {
        return this.promotionTitle;
    }
    
    public void setPromotionTitle(String promotionTitle) {
        this.promotionTitle = promotionTitle;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateof", length=10)
    public Date getDateof() {
        return this.dateof;
    }
    
    public void setDateof(Date dateof) {
        this.dateof = dateof;
    }
    
    @Column(name="promotion_detail", length=65535)
    public String getPromotionDetail() {
        return this.promotionDetail;
    }
    
    public void setPromotionDetail(String promotionDetail) {
        this.promotionDetail = promotionDetail;
    }
    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    @Column(name="locality", length=13)
    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }
    
    @Column(name="award_id")
    public Long getAwardId() {
        return this.awardId;
    }
    
    public void setAwardId(Long awardId) {
        this.awardId = awardId;
    }




}


