package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentScholarships generated by hbm2java
 */
@Entity
@Table(name="student_scholarships"
    ,catalog="qecdb"
)
public class StudentScholarshipsModel  implements java.io.Serializable {


     private Long studentScholarshipsId;
     private CountriesModel countriesModel;
     private InstitutionsModel institutionsModel;
     private CitiesModel citiesModel;
     private String locality;
     private Date year;
     private String nameOfSponsor;
     private Double noOfStudents;
     private String namesOfStudents;
     private String internationalUniversity;
     private String file;
     private Double noOfMale;
     private Double noOfFemale;

    public StudentScholarshipsModel() {
    }

    public StudentScholarshipsModel(CountriesModel countriesModel, InstitutionsModel institutionsModel, CitiesModel citiesModel, String locality, Date year, String nameOfSponsor, Double noOfStudents, String namesOfStudents, String internationalUniversity, String file, Double noOfMale, Double noOfFemale) {
       this.countriesModel = countriesModel;
       this.institutionsModel = institutionsModel;
       this.citiesModel = citiesModel;
       this.locality = locality;
       this.year = year;
       this.nameOfSponsor = nameOfSponsor;
       this.noOfStudents = noOfStudents;
       this.namesOfStudents = namesOfStudents;
       this.internationalUniversity = internationalUniversity;
       this.file = file;
       this.noOfMale = noOfMale;
       this.noOfFemale = noOfFemale;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="student_scholarships_id", unique=true, nullable=false)
    public Long getStudentScholarshipsId() {
        return this.studentScholarshipsId;
    }
    
    public void setStudentScholarshipsId(Long studentScholarshipsId) {
        this.studentScholarshipsId = studentScholarshipsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="countries_id")
    public CountriesModel getCountries() {
        return this.countriesModel;
    }
    
    public void setCountries(CountriesModel countriesModel) {
        this.countriesModel = countriesModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="institutions_id")
    public InstitutionsModel getInstitutions() {
        return this.institutionsModel;
    }
    
    public void setInstitutions(InstitutionsModel institutionsModel) {
        this.institutionsModel = institutionsModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cities_id")
    public CitiesModel getCities() {
        return this.citiesModel;
    }
    
    public void setCities(CitiesModel citiesModel) {
        this.citiesModel = citiesModel;
    }
    
    @Column(name="locality", length=13)
    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year", length=0)
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }
    
    @Column(name="name_of_sponsor", length=250)
    public String getNameOfSponsor() {
        return this.nameOfSponsor;
    }
    
    public void setNameOfSponsor(String nameOfSponsor) {
        this.nameOfSponsor = nameOfSponsor;
    }
    
    @Column(name="no_of_students", precision=22, scale=0)
    public Double getNoOfStudents() {
        return this.noOfStudents;
    }
    
    public void setNoOfStudents(Double noOfStudents) {
        this.noOfStudents = noOfStudents;
    }
    
    @Column(name="names_of_students", length=65535)
    public String getNamesOfStudents() {
        return this.namesOfStudents;
    }
    
    public void setNamesOfStudents(String namesOfStudents) {
        this.namesOfStudents = namesOfStudents;
    }
    
    @Column(name="international_university", length=250)
    public String getInternationalUniversity() {
        return this.internationalUniversity;
    }
    
    public void setInternationalUniversity(String internationalUniversity) {
        this.internationalUniversity = internationalUniversity;
    }
    
    @Column(name="file", length=250)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    
    @Column(name="no_of_male", precision=22, scale=0)
    public Double getNoOfMale() {
        return this.noOfMale;
    }
    
    public void setNoOfMale(Double noOfMale) {
        this.noOfMale = noOfMale;
    }
    
    @Column(name="no_of_female", precision=22, scale=0)
    public Double getNoOfFemale() {
        return this.noOfFemale;
    }
    
    public void setNoOfFemale(Double noOfFemale) {
        this.noOfFemale = noOfFemale;
    }




}


