package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UniDepartments generated by hbm2java
 */
@Entity
@Table(name="uni_departments"
    ,catalog="qecdb"
)
public class UniDepartmentsModel  implements java.io.Serializable {


     private Long uniDepartmentsId;
     private FacultyModel facultyModel;
     private Double code;
     private String name;
     private String detail;
     private Byte isDeleted;

    public UniDepartmentsModel() {
    }

	
    public UniDepartmentsModel(FacultyModel facultyModel) {
        this.facultyModel = facultyModel;
    }
    public UniDepartmentsModel(FacultyModel facultyModel, Double code, String name, String detail, Byte isDeleted) {
       this.facultyModel = facultyModel;
       this.code = code;
       this.name = name;
       this.detail = detail;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="uni_departments_id", unique=true, nullable=false)
    public Long getUniDepartmentsId() {
        return this.uniDepartmentsId;
    }
    
    public void setUniDepartmentsId(Long uniDepartmentsId) {
        this.uniDepartmentsId = uniDepartmentsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="faculty_id", nullable=false)
    public FacultyModel getFaculty() {
        return this.facultyModel;
    }
    
    public void setFaculty(FacultyModel facultyModel) {
        this.facultyModel = facultyModel;
    }
    
    @Column(name="code", precision=22, scale=0)
    public Double getCode() {
        return this.code;
    }
    
    public void setCode(Double code) {
        this.code = code;
    }
    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="detail", length=65535)
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }




}


