package com.qec.model;
// Generated Aug 19, 2017 7:08:20 PM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UniPrograms generated by hbm2java
 */
@Entity
@Table(name="uni_programs")
public class UniProgramsModel extends Model  implements java.io.Serializable {

     private Long uniProgramsId;
     private DepartmentsModel departmentsModel;
     private String code;
     private String name;
     
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="uni_programs_id", unique=true, nullable=false)
    public Long getUniProgramsId() {
        return this.uniProgramsId;
    }
    
    public void setUniProgramsId(Long uniProgramsId) {
        this.uniProgramsId = uniProgramsId;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")    
    public DepartmentsModel getDepartmentsModel() {
		return departmentsModel;
	}

	public void setDepartmentsModel(DepartmentsModel departmentsModel) {
		this.departmentsModel = departmentsModel;
	}

	@Column(name="code", precision=22, scale=0)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
}


